apiVersion: v1
kind: Pod
metadata:
  name: mysql-deploy
spec:
  containers:
  - image: mysql:5.6
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "123456"
    ports:
    - containerPort: 3306
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: monvolume
   
  volumes:
  - name: monvolume
    persistentVolumeClaim:
      claimName: mynfspvc
