apiVersion: v1
kind: Pod
metadata:
  name: monpod
spec:

  containers:
  - name: monnginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: monvolume

  - name: mondebian
    image: debian
    command: ["sleep", "600"]
    volumeMounts:
    - mountPath: /worktmp/
      name: monvolume

  - name: monalpine
    image: alpine
    command: ['sh', '-c', 'echo "Bonjour David" >/myjob/index.html' ]
    volumeMounts:
    - mountPath: /myjob/
      name: monvolume

  volumes:
  - name: monvolume
    emptyDir: {}
