apiVersion: v1
kind: Pod
metadata:
  name: debian-deploy
spec:
  containers:
  - image: debian
    name: madebian
    command: ["/bin/bash","-c","sleep 600"]
    volumeMounts:
    - mountPath: /tmp/
      name: monvolume
   
  volumes:
  - name: monvolume
    persistentVolumeClaim:
      claimName: mynfspvc
