apiVersion: v1
kind: PersistentVolume
apiVersion: v1
metadata:
  name: monpv2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pvdata2"
