apiVersion: v1
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mynfspv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
  nfs:
    server: 192.168.56.102
    path: "/srv/exports"
