apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: monrs
  labels:
    app: monfrontrs

spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: mynginx
        image: nginx
